### ISSUE TITLE
CT: Error: Assertion failed: There should be one pair of parallel sides for a trapezoid

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#108]
```
Uncaught Error: Assertion failed: There should be one pair of parallel sides for a trapezoid
Error: Assertion failed: There should be one pair of parallel sides for a trapezoid
```

**Comment by jessegreenberg** [comment]
Here is a pic of the sim when I hit this error locally:
![image](https://user-images.githubusercontent.com/6396244/161604164-d8d3e508-f5f1-4816-b9ef-223f6d902d55.png)

**Comment by jessegreenberg** [comment]
This is happening because the trapezoid name detection just uses `shapeAngleToleranceInterval` and requires that one pair of adjacent angles add up to Math.PI. But the description for a trapezoid requires that one pair of opposite sides are parallel.

Parallelism uses `angleToleranceInterval`. You can see in this state that `angleToleranceInterval is `-Infinity`, so the two sides will never be parallel.

This seems like a big problem with determining parallel sides. Whenever `angleToleranceInterval` is `-Infinity` we will never have ANY pairs of parallel sides.

**Comment by jessegreenberg** [comment]
To reproduce the problem, 
1) Create a trapezoid by dragging vertices (only vertices!)
2) Modify the trapezoid by dragging a side.

Step 2 will set the `angleToleranceInterval` to `-Infinity` and the shape will no longer have any parallel sides within that tolerance interval.

I made a commit to fall back to something instead of crashing until we can discuss what to do.

**Comment by jessegreenberg** [comment]
@BLFiedler suggested that we try removing the `+Infinity` and `-Infinity` tolerance cases now that positions are constrained to a grid. They may not be necessary.

**Comment by BLFiedler** [comment]
**Slack Log for posterity:**

> TS
The more we talk about shapes, I am starting to think some shapes should be in the actual responses.
[2:41](https://phetsims.slack.com/archives/GUXFY1NQ2/p1649097682826699)
But maybe that is like giving the answer.

BF
I believe is it more "giving the answer" if you provide a name and then list the specific qualities that differentiate it from other shapes. e.g., "This is a trapezoid, it has exactly one set of parallel sides." without any other info.

But I also don't think that the "name" is as important as the property. "What is parallel and why is one pair parallel but the other is not" are what we want people to try to glean (edited) 


Going to try to read the paper Dor recently sent that might help understand students failure points in recognizing these properties, hopefully sooner rather than later :slightly_smiling_face:
https://www.tandfonline.com/doi/full/10.1080/0020739X.2022.2052196

can you remove the -infinity tolerance for a build to see if it feels as relevant with the new tolerances and new position restriction?

JG
Sure! Both -Infinity and +Infinity cases?

BF
And, it may not be different, but do we think we'll hit the same problem if we institute the other parallel definition for both trapezoid and parallellogram? (1x adjacent complementary and 2x adjacent complementary respectively)

Sure! Both -Infinity and +Infinity cases?
Why not. Maybe it will help us finesse out a better method.

**Comment by jessegreenberg** [comment]
Here is a version with this change: [dev.colorado.edu/html/quadrilateral/1.0.0-dev.26/phet/quadrilateral_en_phet.html?showModelValues](https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.26/phet/quadrilateral_en_phet.html?showModelValues)

I reverted the change in master, we can commit to it if we like it.

**Comment by jessegreenberg** [comment]
There was a substantial sound bug in the link posted above, here is a version with this change with that fixed: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.27/phet/quadrilateral_en_phet.html

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/quadrilateral/issues/108#issuecomment-1088908994 does not work because there are NO parallel sides when the `angleToleranceIntervalProperty` is `-Infinity`. Ill consider changing `angleToleranceIntervalProperty` to work for pairs of sides instead of the entire quadrilateral like we discussed during meeting today.

**Comment by jessegreenberg** [comment]
OK, this is done and it seems to be working well. The steps in https://github.com/phetsims/quadrilateral/issues/108#issuecomment-1087885985 are no longer a problem. Instead of a single `angleToleranceInterval` for parallelogram, there are now two `angleToleranceInterval`s, one per opposite side pair. They behave similarly to https://github.com/phetsims/quadrilateral/issues/26#issuecomment-1015822193, but change depending on the state of parallelism with the opposite side instead of whether it is a parallelogram.

I added some more info to the debugging tab to demonstrate this with `?showModelValues`
![image](https://user-images.githubusercontent.com/6396244/162001761-3182a480-95e5-4b42-ba85-710482230177.png)

@BLFiedler can you please review?

**Comment by BLFiedler** [comment]
Great! One thing I've noticed (that I'm not sure we addressed in our discussion of this yesterday):

Are we missing the -infinity behavior from before? I'm still able to drag a side as a trapezoid and make a parallelogram I think it probably behaves differently now, but I think what might need to happen is if (AB,CD) are parallel, then (BC,DA) needs to become -Infinity for a trapezoid. I think?

https://user-images.githubusercontent.com/47331395/162010852-120df851-2379-40c9-8210-4d830632b78d.mp4

**Comment by jessegreenberg** [comment]
Hmm, good find...yes it seems like we need to support that case. If one side is parallel and is being dragged, the other pair needs to have its tolerance interval set to `-Infinity` if it is not parallel so this doesn't happen.

**Comment by jessegreenberg** [comment]
Some vertex positions where I can get this to happen consistently by setting to this value and then moving the top side to the right.
![image](https://user-images.githubusercontent.com/6396244/163834704-da805b74-5915-4729-bbe3-d85342cfb852.png)

**Comment by jessegreenberg** [comment]
I think we need a totally different implementation than I tried in https://github.com/phetsims/quadrilateral/commit/8708ff96f0a70d2a26eb413f8bf7e6255aedadaf because the tolerance interval of each opposite side pair needs to be dependent on the interaction and `isParallel` state of the other opposite side pair. We need a type that combines them so they can query eachother.

**Comment by jessegreenberg** [comment]
Actually I was able improve this without changing much, here is the new logic added to the "angleToleranceInterval" calculation:

```js
        if() { /**...**/}
        else if ( anyOtherSidesPressed && !this.isParallelProperty.value ) {

          // The other sides are being pressed and my sides are not currently parallel. While dragging a side we
          // do not want the shape to become a parallelogram within a finite angleToleranceInterval so make sure
          // my sides will never become parallel.
          toleranceInterval = Number.NEGATIVE_INFINITY;
        }
```

@BLFiedler can you please review and test again?
