### ISSUE TITLE
Increase the pointer areas for vertices?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#125]
I think at one point vertex mouse/touch areas used to be larger. I removed the larger touch areas when we added sim graphics. But after playing with the sim I am finding that change makes it difficult to grab vertices. @BLFiedler what do you think about increasing the mouse/touch areas for the vertices?

**Comment by BLFiedler** [comment]
Are you trying this on a laptop/tablet or mobile touchscreen?

Either way, I agree we could extend it past the graphical bounds of the vertex. Is there a precedent for how far out is reasonable to extend the radius of touch interaction?

**Comment by BLFiedler** [comment]
Noting visual here for posterity. 

![image](https://user-images.githubusercontent.com/47331395/166310610-6afd3bc0-6d04-4996-969f-25214c382c62.png)

Feels fine to me. Before I close the issue, @jessegreenberg , can you note what happens when the pointer areas overlap? Does it prioritize the last dragged vertex or the tab order?

**Comment by jessegreenberg** [comment]
By default it uses the z order, whichever is on top which happens to be the order components are added to the view in code. So the priority will be D over C over B over A. That happens to be the reverse of the tab order.

Let me know if that needs to change.  We could move the dragged vertex to the top. We could also just increase the size and reduce the touch areas so that the touch areas cannot overlap.

**Comment by BLFiedler** [comment]
I think it is fine until it isn't :) Good to note here though. Thanks!
