### ISSUE TITLE
Dynamic tolerances revisited: Tangible input, Computer Vision, and Multitouch

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#247]
We have several tolerances in place and they vary depending on what input method we have at any given time. Let's try to simplify them and instead apply a scaleFactor depending on the input method.

@jessegreenberg, can you list all existing tolerance values and which ones are currently being modified based on input or selection? If simple, their current values as well.

**Comment by terracoda** [comment]
While testing object responses in #237 
I hear a tolerance issue here where as Corner C becomes a right angle, it is described as "similar but smaller than Corner B". However, if I click on Corner C, I get the correct description, "equal to one adjacent corner".
Maybe we just are not applying the tolerances in all the same cases?
<img width="905" alt="image" src="https://user-images.githubusercontent.com/1902116/196561466-ad9ad899-1899-4554-8fc8-26bb64a1d362.png">

**Comment by terracoda** [comment]
I cannot reproduce the above case today, so maybe I interpreted what I heard incorrectly :-)

**Comment by jessegreenberg** [comment]
Listing out everything as of 10/19/22.

- `parallelAngleToleranceInterval` - default 0.01
  - The tolerance interval for angle comparisons when determining if two sides are parallel.
- `deviceAngleToleranceInterval` - default 0.02
  - The tolerance interval for angle comparisons when determining if two sides are parallel while the sim is connected to a tangible device.
- shapeLengthToleranceInterval - default value 0.01
  -  Tolerance interval for comparing lengths of the shape, mostly used to determine shape name.
  - Would probably be best to rename to `interLengthToleranceInterval` 
- `toleranceIntervalScaleFactor` - default value 10
  - A scale factor applied to `deviceAngleToleranceInterval` when the sides are parallel.
  - A scale factor applied to `parallelAngleToleranceInterval` when two vertices are pressed at once.
  - A scale factor applied to `interAngleToleranceInterval`, `staticAngleToleranceInterval`, `shapeLengthToleranceInterval` when connected to a tangible device AND there is a detected shape name. Note there is now always a detected shape name because we fall back to convex quad.
- `interAngleToleranceInterval` - default value 0.02
  -  The tolerance interval for angle comparisons when comparing one angle to another (except for checking for parallel).
- `staticAngleToleranceInterval` - default value 0.01
  - The tolerance interval for comparing an angle to a constant value like PI / 2.
- `fineInputSpacingToleranceIntervalScaleFactor` - default value 0.02
  -  A scale factor applied to `parallelAngleToleranceInterval`, `interAngleToleranceInterval`, `staticAngleToleranceInterval`, `shapeLengthToleranceInterval` when "Fine Input" is checked in preferences.
  - **COMPOUNDS with `toleranceIntervalScaleFactor`**
- `deviceStaticAngleToleranceInterval` - default value 0.01
  - The base value for `staticAngleToleranceInterval` when connected to a device.  
- `deviceInterAngleToleranceInterval` - default value 0.001
  -  The base value for `interAngleToleranceInterval` when connected to a device.
- deviceShapeLengthToleranceInterval - default 0.02
  - The base value for `shapeLengthToleranceInterval` when connected to a device.
- lengthToleranceIntervalScaleFactor (I think this one is not used anymore?) - default 0.05
  - Scale applied to the length of a side such that the Side's length tolerance interval is `length * lengthToleranceIntervalScaleFactor`.
  - **I don't think this is being used anymore. **


😨

**Comment by jessegreenberg** [comment]
I would love to see all of the device tolerance intervals replaced with the position intervals we added when we last worked on device connection. I think ideally the device would have no bearing on the model or shape detection, but changing where vertices snap to makes it easier/harder to detect shapes with that input form.
<details>

![image](https://user-images.githubusercontent.com/6396244/196755334-17d4253d-2ad4-4874-88d8-195b78344948.png)

</details>

**Comment by BLFiedler** [comment]
We have a rather extensive list of tolerance intervals and query parameters tied to those.

I'd like to align the input tolerances as much as possible, but only where it makes sense to and of course eliminate those not in use.

As always, the interplay between tolerances and step-size is tricky. Necessarily, large step sizes eliminate the possibility of finding certain shapes at small tolerances intervals. In some ideal, unrealistic world, every tolerance would be ideally tuned to each step-size such that any shape was achievable, but no set of vertex positions would reveal the inaccuracy of the shape.

In the absence of that, it'll be better to keep the tolerances relatively consistent and adjust the input step-size and accept the loss of shape detection.

Re: dynamic tolerances (ones that open up when certain components are in motion). The benefit of this is mostly when the step size is relatively small (less than expected variance in how someone moves/wobbles as they change e.g., a vertex position) but the intention behind the movement is clear (e.g., two vertices moving to maintain a parallelogram). These are not universally applicable to all shapes. 

Shape maintenance is also impacted by step-size and tolerance. There are certain shapes for which certain orientations are easier to maintain at larger step sizes. A kite is easy to maintain at larger step sizes when the "top" and "bottom" vertices that define the diagonal symmetry are either horizontally or vertically aligned, which is NOT the case when the sim is set to the default square. Maintaining a parallelogram becomes more difficult at higher step-sizes as individual vertices step over when dragging a side causing momentary transitions to a trapezoid.

No to-dos here. Next post here I'd like to list each of our anticipated inputs, what their step-sizes and tolerances are, and see what can be condensed/aligned.

**Comment by BLFiedler** [comment]
The goals of the simulation have shifted from dynamic shape maintenance at the beginning of our research-focused explorations. With a focus on shape to shape transformation and identification of key properties, we do not need to continue to support embodied maintenance at the cost of shape accuracy.

Goals of this issue going forward:

1. Remove specific device tolerance intervals. Reduce to a single scale factor, e.g., `connectedToleranceScaleFactor`. Establish this as a query parameter that we will leave for publication and reference in documentation about the external device connection/OpenCV capabilities. I think this is replacing `toleranceIntervalScaleFactor` and removing `deviceAngleToleranceInterval`, `deviceStaticAngleToleranceInterval`, `deviceInterAngleToleranceInterval`, and `deviceShapeLengthToleranceInterval`.

2. Remove all tolerances and code intended to support "dynamic" maintenance of shape. Shape maintenance is supported primarily through step size and existing tolerance scaleFactor. I think this will remove `lengthToleranceIntervalScaleFactor` **and** remove the temporary increase in tolerance when multitouch occurs. 

3. Another pass on cleaning up and renaming intervals to keep clarity.

I think in effect the totality of these changes will result in a list that looks more like this:


![Image](https://user-images.githubusercontent.com/47331395/201982486-e62a5b0d-92db-4b4c-b4e0-de48b44fcc49.png)

Let's discuss at next model meeting and I'll create actionables based on the above ideas.

**Comment by jessegreenberg** [comment]
OK thanks. No need to remove it in my opinion, intent still seems different. Maybe someday we will want the values to be different. I just wanted to make sure this result was correct after the above changes. Anything else for this one?

**Comment by BLFiedler** [comment]
Sounds good to me. Closing!
