### ISSUE TITLE
Update MediaPipe support for latest version

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/quadrilateral#258]
The quick mediapipe implementation for this sim done by @jessegreenberg has been useful as a demo multiple times! Last known (to me) link runs off 1.0.0-dev.40.

Let's assume it will continue to be so and bring it forward to the latest Quad version that supports full shape detection. 

We can leave detection to tips of thumb and index fingers (I'm assuming 4 & 8 based on reference below?)
![image](https://user-images.githubusercontent.com/47331395/200705497-c08cbe20-9709-4295-abea-316216641496.png)

- [x] We'll want to update the terminology/query parameter to match the feature as it is now used in Ratio and Proportion: `?cameraInput=hands` and continue to support `?showVideo`
- [x] Let's plan to use default tolerances and let it reside on the input grid (and be responsive to the Fine Input Spacing checkbox).

**Comment by BLFiedler** [comment]
Not ahead of publication, but perhaps for May 2023 convening.

**Comment by BLFiedler** [comment]
Let's port over the Input Tab from Ratio and Proportion Camera Input Hands. @BLFiedler & @terracoda will need to reword for Quadrilateral.

**Comment by terracoda** [comment]
How's this? Assuming Y-Axis and X-Axis reflect camera position.
I added "gestures and", since hand gestures can differ as well as movements, but maybe that it not relevant here.
I added "or groups of objects" because int eh case of Quad, fingers on the right hand are controlling the 2 vertices on the right side of the shape. It seemed more like a group of objects (2 vertices and a side) being controlled by a single hand.

### Camera Input: Hands
Use custom hand **_gestures and movements_** to control **_objects_** in the sim.

Input Device: [ FaceTime HD Camera]

### Troubleshooting Camera Input: Hands
If needed, use the options below to change the behavior of the sim **_objects_** to match your hand movements. 

Are your hands mapped to the wrong **_object or group of objects_**? 
[ ] Flip camera Y-axis

Are your hands moving the **_sim objects_** in **_what seems_** like the wrong direction? 
[ ] Flip camera X-axis

**Comment by terracoda** [comment]
Please note that we are not currently Voicing, the label "Input Device" for the combobox in Ratio and Proportion. Can we fix that when we publish this dialog? Maybe there is a reason "Input Device" is not Voicing on focus?

I think it should work like the Range combobox in RaP, but I'll check.

**Comment by BLFiedler** [comment]
I like the more general language. I am not sure if the statements for each option will always map to future contexts, but they make sense here (y-axis flips which hand, x-axis flips index/thumb mapping). 

I wonder if we should make the decision to always use the Teacher Tips to give the exact mappings and make a general statement in the tab directing to them? There's just no way to know in the sim what is mapped to what, but we don't want to change the pref menu every time if we could possibly generalize it (I think?)

**Comment by terracoda** [comment]
I like that idea @BLFiedler, and was wondering about that, too. I'll update the text.

**Comment by terracoda** [comment]
@jessegreenberg, assigning to you for implementation.

**Comment by BLFiedler** [comment]
This will be a local change for Quadrilateral. We need to consider putting the new language on the Input tab into common code, but this isn't a decision to make at the moment as it would change RaP's code and reset translations for the sim. We should create an issue in the tangible repo to address this in the future when CI:H is being put into another sim.

**Comment by BLFiedler** [comment]
- [ ] Hide calibrate buttons when CI:H enabled. Don't show Input tab specific to ?deviceConnection.

**Comment by jessegreenberg** [comment]
I added options to the MediaPipe content in common code to support custom strings and adjusted the layout because these strings are much longer.

- @terracoda can you please review the dialog content and the Voicing?
- @BLFiedler @terracoda can you please review the change to snap the vertices to the major interval? Do you find it working well or too coarse?
- @BLFiedler can you please test the "Flip Camera..." settings for camera input? I was able to test default and when BOTH X and Y are flipped. But could not test X/Y flipped independently.

Also as discussed, when camera input is used, all device/bluetooth controls are hidden from ScreenView and preferences.

I think that is it! Anything else?

**Comment by jessegreenberg** [comment]
I can't just "flip" the positions with the camera because that produces an invalid shape. Vertices A, B, C, D must be in that order moving clockwise. So each camera flip is a rotation of the finger mapping. I used https://webcamtests.com/mirror to figure out which finger should map to which vertex with combinations of camera flipping. Here is what I ended up with:

        // flip x
        // left thumb a
        // right thumb b
        // right index c
        // left index d

        // flip y
        // right index a
        // left index b
        // left thumb c
        // right thumb d

        // flip both
        // right thumb a
        // left thumb b
        // left index c
        // right index d

But this is still not working.

**Comment by terracoda** [comment]
There are issues with the Voicing.
There are no context responses for the checkboxes.

I went to check RaP's checkboxes and the words seemed to have changed. The trouble-shooting questions are no longer there: 
![Screen Shot 2023-06-02 at 7 00 27 PM](https://github.com/phetsims/quadrilateral/assets/1902116/04f7c48e-c3f8-4d44-a697-c5d49f6b2014)

I'll check the design doc to see if there are any designed context responses.

**Comment by terracoda** [comment]
Here's Quad's dialog for comparison:
![Screen Shot 2023-06-02 at 7 06 01 PM](https://github.com/phetsims/quadrilateral/assets/1902116/0fa43a4f-2dcd-4b81-aa46-27a15419b2cc)

**Comment by jessegreenberg** [comment]
Thanks @terracoda - I used the wrong default strings for the options when I changed the common code component. Fixed in the above commit.

I hear context responses for these checkboxes when context responses are enabled in the Preferences dialog. Can you confirm?

**Comment by terracoda** [comment]
After checking "Voice surrounding context changes", I hear them, but that is not how check boxes in the Preferences dialog are supposed to work. The check boxes for Sim Voicing Options are for the Sim. In the Preferences dialog, we should always hear all responses that we design. They can behave a little differently than sim check boxes because they are meant to confirm settings for all users including learners who are blind who are using Voicing.

There were no context responses in the design docs, so I added the ones I heard. It's possible those were added after I reviewed RaP's initial implementation.

**Comment by terracoda** [comment]
To be clear, the check boxes in the Preferences Menu have a custom Voicing behavior. I have mentioned this before, so I am wondering how we should document this difference.

**Comment by terracoda** [comment]
For example, if you review the Voicing behaviour of the check boxes under Sim Voicing Options, you'll see they always get their context responses whether or not the context response checkbox is checked.

**Comment by terracoda** [comment]
@jessegreenberg, is there an option for check box to not pay attention to the checked sim voicing options and just always voice the context response?

**Comment by terracoda** [comment]
I think, the reason for the difference is because there is name name response for pointer-based input for these check boxes, so if there is no context response, nothing at all is voiced with pointer-based input when the check box is checked and unchecked.

**Comment by jessegreenberg** [comment]
Oh right! Sorry, I forgot about that behavior. We have an option for anything that can voice to speak all responses regardless of user settings. I added it to these checkboxes in the above commit. Sorry, we don't have a way to do it for all Preferences content at once so we will need to remember to add this to every UI component individually. It might be nice someday to make this more automatic.

Anything else for the voicing or dialog?

**Comment by terracoda** [comment]
Oh, when I hit escape on the Device Input combobox, the dialog closes.
Escape key should close/dismiss the open combobox if it has focus. 

It works correctly for the Voice combobox.

**Comment by terracoda** [comment]
For giggles, I tried exploring the dialog with VoiceOver. Likely due to system resource overload, I get a lot of "Safari not responding" when using both VoiceOver and the query parameter for Camera Input: Hands.

When I was not using camera input, Safari and VoiceOver seemed to work fine navigating through the Preferences dialog.

**Comment by jessegreenberg** [comment]
Good catch @terracoda, thanks. This is a problem with ComboBox. It is working well for the voice ComboBox by accident because of the way the scene graph is structured there. I added an `abort` to the keyboard event handler in ComboBox to prevent the event from being passed to the dialog. This is fixing it for me. Can you please confirm?

**Comment by terracoda** [comment]
The combobox is now closing properly in all browsers on MacOS.

**Comment by terracoda** [comment]
The write-up is good.

Re image. I think it works, but there are 2 things we should consider: 
- Sarah already has some artwork of animated hands that she is using in the video for camera input. It might be best to use the same artwork?
- Does it make sense to super-impose an image like the one you have above in front of an image of the sim, .e.g. the sim showing an Isosceles Trapezoid like what you have in the current image?

The text all looks good.

**Comment by brettfiedler** [comment]
Uploaded new teacher tips alongside the URL fixes in #451 . Closing.
