### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#27]
Convert the existing sim to TypeScript. This is a good sim to do this because we are early in the development cycle. Porting should be relatively quick and new code can be written with TypeScript.

Issue is to track commits and questions.

**Comment by jessegreenberg** [comment]
One downside of this conversion will be that feature branches like #21 #18 and @17 will be difficult to merge back in. But that is OK, I think there is a low chance that we will need to merge. Work in those issues can be re-implemented in master with TypeScript.

**Comment by jessegreenberg** [comment]
Timing compilation, first time it compiled with `grunt output-js-project` it took 18 seconds
```
$ grunt output-js-project
Running "output-js-project" task
>> TypeScript compilation complete: 18093ms

Done.
```

Second compilation takes about  2 seconds
```
$ grunt output-js-project
Running "output-js-project" task
>> TypeScript compilation complete: 2026ms

Done.

```

**Comment by jessegreenberg** [comment]
Questions:
> Please make sure you are using the commit hooks, which are configured to run type checks on typescript repos.

I have hooks set up for lint and unit tests as described in the development overview, I am not sure if I need to reinstall hooks with this change. Ill test it out to see.

**Comment by jessegreenberg** [comment]
The conversion to TypeScript is complete with the exception of usages of Enumeration, EnumerationProperty, options, and strings. 36 TODOs were added to the code for things that are unsolved. They mostly involve options, Enumeration, mixin/trait, and un-ported common code. Issue https://github.com/phetsims/quadrilateral/issues/27#issuecomment-960017873 is my collection of questions so far.

I will leave this open because there are things to return to as TypeScript progresses in the project.

**Comment by samreid** [comment]
> 2) Best practices for using inferred types vs explicit?

@chrisklus and I wrote our recommendations in https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md

> Best practices for annotating public when it is default?

At a dev meeting, we decided this is developer preference.

> 3) Will import statements change? We convert .js to .ts, but import statements still use .js suffix.
  EDIT: I guess probably not, the .ts files are "compiled" to .js, so that is likely what ends up getting imported.

For our stack to work, we require the *.js suffixes even though it is *.ts files.

> 4) Where does documentation go for class properties? In the definition or in the constructor?

This would be good to discuss.  Perhaps documentation about what it is and how it is used should be in the definition.  Documentation about its initial value should be in the constructor?

> 5) Surprising that `readonly` means that I cannot set the property in instance methods of the class. Is there a TypeScript equivalent to our `@public (read-only)`?

There is a working proposal for `ReadOnly<Property>` in https://github.com/phetsims/axon/issues/363.  There is no built-in language feature to "freeze" a TypeScript object.

> 6) Are there any TypeScript annotations for methods? That would be handy.
EDIT: There sure are!

I'm not sure what kind of annotations you are referring to.

> 7) So far I am skipping typescript for options, enumerations, and Maps. Maps could actually be straight forward but my Maps use Enumeration. ACtually, my Enumerations could probably use Enumeration.byValue instead of maps.

Several developers are using the Enumeration patterns described in https://github.com/phetsims/wilder/blob/master/js/wilder/model/WilderEnumerationsTypescriptTestModel.ts and it is working well.  Some discussion and fine-tuning is at https://github.com/phetsims/chipper/issues/1106

The options pattern described in https://github.com/phetsims/wilder/blob/master/js/wilder/model/WilderOptionsTypescriptTestModel.ts is working well and may be slightly fine-tuned, but that's a reasonable starting point.

Map should be used as `Map<Key,Value>`.  Yes, to use it with enumerations you may wish to port the enumerations first.

> 8) Just noticing this nice flag that the instanceof check is redundant, Ill be removing these in this sim:
![image](https://user-images.githubusercontent.com/6396244/140234323-b72c5fc0-2a49-4a98-9d9f-6fdc3f7e6c8d.png)

Nice!

9) If I have an Emitter like this defined:
```
public shapeChangedEmitter: Emitter<[]>;
```
Why does TypeScript allow this?
```
this.shapeChangedEmitter = new Emitter();
```
instead of require this?
```
this.shapeChangedEmitter = new Emitter<[]>();
```

Great question that I don't fully understand.  `const x = new Emitter()` infers as type `Emitter<unknown>`.
Perhaps the declaration `Emitter<[]>` is used to disambiguate?  I'd like to learn more about this but I'm not sure how.

> 10) Where does the type alias go? Top of file, after constructor, its own file?

Probably any of the above, depending on context.  Type aliases used in one file, could be defined locally.

> 11) I am not sure how to handle usages of the Voicing and ParallelDOM traits.

For ParallelDOM, we will ts-ignore until we get better TypeScript support for those in common code.  I'm not familiar with Voicing.

> 12) I have an Enumeration and an EnumerationProperty in the model. In the view I was able to reference the Enumeration through `enumerationProperty.enumeration`. But I need the Enumeration type in the view now for TypeScript. Should I export the Enumeration or turn it into its own file? I also cannot use MyModel.MyEnumeration as a static because I get
`TS2702: 'MyModel' only refers to a type, but is being used as a namespace here.` For now I am going to export the Enumeration instead of create a separate file for it. See `export { SuccessSoundFile };` in QuadrilateralSoundOptionsModel.ts.

After porting enumerations following https://github.com/phetsims/wilder/blob/master/js/wilder/model/WilderEnumerationsTypescriptTestModel.ts, EnumerationProperty is no longer necessary. But we may use something like RichEnumerationProperty or StringEnumerationProperty (in wilder).

> 14) Should we use single variable or multivariable import statements?
`import CircuitElementViewType, { CircuitElementViewTypeValues } from './CircuitElementViewType.js';` vs
```
import CircuitElementViewType from './CircuitElementViewType.js';
import CircuitElementViewTypeValues from './CircuitElementViewType.js';
```

If multiple variables per import, WebStorm breaks it into multiple lines:
```js
import QuadrilateralSoundOptionsModel, {
  SuccessSoundCollection,
  SuccessSoundFile
} from '../model/QuadrilateralSoundOptionsModel.js';
```

This breaks a lint rule. It is also what WebStorm does by default.

This may be good to discuss as a team.

> 15) Same question as 14 for exports.

This may be good to discuss as a team.

> 16) Similar question to 12, but for an inner class. I have an inner class called SuccessSoundCollection in QuadrilateralSoundOptionsModel.  Instances of SuccessSoundCollection are the value for a model Property. A listener on that Property in another class and file handles the changing value. Now with TypeScript, I need to declare the SuccessSoundCollection as the type for the listener. Does this mean that SuccessSoundCollection should not be an inner class? Should it be exported by the file it is declared in or should it be its own file now? I am exporting it from the file it is declared in for now.

A separate file for that sounds appropriate, since it will be used in more places now.

**Comment by samreid** [comment]
I wrote up responses to many of the points in the previous comment.  If you would like to discuss further, or collaborate on Enumeration or Options, please reach out to me on Slack.

**Comment by samreid** [comment]
I added these conventions in the commit:

### Documentation for Class Properties

Documentation for class properties should be placed with the declaration, not the instantiation. See, for
example https://github.com/phetsims/geometric-optics/blob/03e5637eb16600dd329e20f32fafc3ab99922c8a/js/common/model/GeometricOpticsModel.ts

```ts
class Person {

  // First and last name separate by a whitespace
  readonly name: string;

  constructor( name: string ) {
    this.name = name;
  }
}
```

### Multiple Exports in One Expression
Multiple exports should be combined into one expression.  This is advantageous for the same reason we often prefer
to have one return statement from functions.

```ts
// Recommended
export { CircuitElementViewType as default, CircuitElementViewTypeValues };

// Not recommended
export default CircuitElementViewType;
export { CircuitElementViewTypeValues };
```

### Multiple Imports in One Expression
Multiple imports from the same file should be combined into one expression.  This helps clarify that they are related.

```ts
// Preferred
import BendingLightScreenView, { BendingLightScreenViewOptions } from '../../common/view/BendingLightScreenView.js';

// Not preferred
import BendingLightScreenView from '../../common/view/BendingLightScreenView.js';
import { BendingLightScreenViewOptions } from '../../common/view/BendingLightScreenView.js';
```
If this exceeds the line limit and the WebStorm formatter wants to format it on multiple lines, please use
`// eslint-disable-line single-line-import`

**Comment by jessegreenberg** [comment]
Thanks for reviewing this @samreid, I appreciate the comments. THis is no longer on hold and I think we are at a point now where pretty much all todos for this issue can be addressed.

**Comment by jessegreenberg** [comment]
The new options and enumeration patterns are now used in this repo. The only `@ts-ignore`s that remain involve `phetAudioContext` and options that go along to components that compose Voicing (trait pattern).

**Comment by jessegreenberg** [comment]
`@ts-ignore`s related to sound/tambo have been resolved. The only remaining ones are related to experimental bluetooth features that are not available in Typescript built-in types and I think its OK for those to stay since we don't know what will become of that feature.

Closing this mega-issue, new TypeScript improvements can happen in new smaller issues.
