### ISSUE TITLE
Turning off Sounds doesn't disable Shape Sound Options

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#324]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/879, shouldn't turning off Sounds gray out Shape Sound Options?

**Visuals*
<img width="530" alt="Screenshot 2023-01-10 at 2 09 09 PM" src="https://user-images.githubusercontent.com/87318828/211640694-484a5237-a5f7-496c-9a96-2846fbdcdba7.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.73 2023-01-08 23:48:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1475x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Good point @Nancy-Salpepi, yes it should. That would match the 'Extra Sound" enabled checbox becoming disabled when Sounds are disabled.

**Comment by jessegreenberg** [comment]
I am running into a problem with our support in joist for this :( The opacity is compounding when I set `enabled` on a child of the audio content like this:

![image](https://user-images.githubusercontent.com/6396244/211681475-c49c28bf-97af-4c38-a214-52b340ca810b.png)

Ideally, AudioPreferencesPanel would set `enabled` for us on custom preferences so this isn't a sim issue in the first place. But there is nothing about how customPreferences are added right now that separates custom voicing preferences vs custom sound preferences so...we would have to redo a lot in common code.

I discussed with @marlitas and it is likely that there will be so much change to this dialog layout that it isn't worth improving in common code right now.

One workaround is to make Shape Sounds options invisible when sound are disabled. It actually looks nice because it matches the Voicing column! @BLFiedler @terracoda are you OK with that? If not I can look into a different approach.

**Comment by jessegreenberg** [comment]
Making invisible was pushed to master if you want to see how it looks.

**Comment by BLFiedler** [comment]
This works for me. @terracoda , feel free to review and close.

**Comment by terracoda** [comment]
Looks good to closing.

**Comment by terracoda** [comment]
I had one concern that about what to do in the Preferneces menu if the Shape Sound checkbox is unchecked, but since that interaction is controllable in the sim, I think that's perfect as-is. The state of the checkbox should not affect the Preferences menu.
