### ISSUE TITLE
Support dynamic locales

### ISSUE THREAD

**Issue by samreid** [phetsims/quadrilateral#399]
During code review #398, @matthew-blackman @jessegreenberg and I discovered that the sim strings do not dynamically adjust when the locale is changed at runtime.  We tested this via `?stringTest=dynamic` then using the arrow keys.  The reviewers recommend that we should take the time now to support dynamic locale.  It does not look like a very large number of strings on the screen.

@jessegreenberg indicated a previous decision that we did not have time to support dynamic strings for this sim.

@jessegreenberg indicated that this is also moving toward a production publication, not a prototype publication.  For me, this is even more reason to support dynamic strings.

@jessegreenberg wanted to run this past @kathy-phet before spending time on it.

**Comment by kathy-phet** [comment]
Yes, please support dynamic locale. @jessegreenberg - You have my support/time to spend time on this. Thanks!

**Comment by jessegreenberg** [comment]
OK, thanks @kathy-phet! I have added this to the dim sum items for this iteration. This should be a quick task but we will report back if it gets very complicated due to the large number of Voicing strings.

**Comment by jessegreenberg** [comment]
string -> StringProperty done in the above commit, ready for layout changes. Using `locales=*&stringTest=dynamic&dev` It looks like Vertex labels need to re-center and the "ResetShape" button needs to be re-centered upon string change.

**Comment by arouinfar** [comment]
@jessegreenberg I tested this thoroughly with `stringTest=dynamic` and I'm not seeing any layout issues. Everything looks great! 

Also, I just want to note that `stringTest=dynamic` is a really useful tool. It's much more efficient than cycling through existing locales or customizing the strings in Studio. 

My schedule didn't line up with @terracoda, but I shared a link to the documentation in [initialize-globals](https://github.com/phetsims/chipper/blob/master/js/initialize-globals.js#L612-L626) over Slack. I think it's a pretty low barrier to entry, but happy to consult on any future dynamic locale review needs.

Since I don't have any change requests, I think we're good to close.
