### ISSUE TITLE
Everything moves when corner/side hits edge on Chromebook

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#432]
**Test device**
Chromebook

**Browser**
chrome 112.0.5615.134

**Problem description**
For https://github.com/phetsims/qa/issues/926, when I move a corner or side so that it hits the edge of the play area, everything shift a bit.

**Steps to reproduce**
1. Grab corner "A" and hit the left side of the play area

**Visuals**
Hard to see everything shifting in this video. Focus on the letters in "Shape Name Hidden" and the words "Small Steps"

https://user-images.githubusercontent.com/87318828/233424660-628eb127-ec4f-4506-84df-44797a4ad8be.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-rc.2/phet/quadrilateral_all_phet.html
Version: 1.0.0-rc.2 2023-04-04 16:04:39 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1472x775
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
I have a Samsung ChromeBook with version 112.0.5615.134 and I was not able to reproduce this unfortunately. I tried a few different window sizes. It is probably pretty machine dependent.

This is actually another case of https://github.com/phetsims/scenery/issues/1289. According to that issue `preventFit` on the right component might fix this. Im going to try the QuadrilateralNode itself because I think its the "blocks" around that drawable that are changing certain rendering bounds (I don't really understand how preventFit works).

@Nancy-Salpepi can you please try master again on the machine you found this and see if it is fixed?

**Comment by Nancy-Salpepi** [comment]
This looks fixed on master!

**Comment by jessegreenberg** [comment]
Great, thank you for checking @Nancy-Salpepi . I will cherry-pick into release branch.

**Comment by stemilymill** [comment]
Seems fixed to me!
