### ISSUE TITLE
Need common code implemented for Reset All button

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#44]
Verified in meeting.

**Comment by terracoda** [comment]
Not hearing the the Reset All context response when pressing Reset All button. Hearing changed sides instead.

**Comment by jessegreenberg** [comment]
Ah, this is happening because model updates happen in this sim in the animation frame. So the code in ResetAllButton is not preventing this. The UtteranceQueue is disabled when the ResetAllButton is pressed, then reenabled. The next animation frame some model properties change and voicing responses are spoken then.

I think one way to fix this is to update the asynchronous Properties at the end of the reset operation.

**Comment by jessegreenberg** [comment]
That was part of it, but I also needed to update the QuadrilateralAlerter to not alert next frame when it detected that it should after Properties changed from a reset.

I think this is fixed, can you please confirm @terracoda?
