### ISSUE TITLE
The electron app should only set vertex positions when the data looks reasonable

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#46]
@BLFiedler and @terracoda demonstrated today that there are times where the values are NaN. The electron app sends bad data to the sim. We should prevent sending bad data in the app and the sim should not set bad values to the vertices.

**Comment by jessegreenberg** [comment]
Also, it seems like the bad values are coming from the electron app. We should investigate why it is sending bad values.

**Comment by jessegreenberg** [comment]
I just updated both the sim and the app to effectively no-op when values are NaN, less than zero, undefined, or null. The dot next to "Good data" should turn red if the data is no good.

I built new versions of the app and uploaded to https://drive.google.com/drive/folders/19SnDQE2STxSu2CpjqaAHEfODU7r44pLF.

@BLFiedler can you please try this new version of the app?

**Comment by BLFiedler** [comment]
Great - I think this is working correctly from the app-side. It highlights some of the incorrect values coming in for the device and sensors defects in a way I think will be helpful.

https://user-images.githubusercontent.com/47331395/150389899-097df610-67b1-44cf-87ec-05ec33fec244.mp4

Also highlights some things to bring up regarding or tolerances, but that is a discussion elsewhere.

Closing. Thanks Jesse!

**Comment by brettfiedler** [comment]
We lost the link to the app during the Google Drive migration. Updating this issue in case we come looking again. [It is here now](https://o365coloradoedu.sharepoint.com/:u:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Accessibility/Research/Tangibles/Quadrilateral/[my-electron-app-win32-x64.zip](https://o365coloradoedu.sharepoint.com/:u:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Accessibility/Research/Tangibles/Quadrilateral/my-electron-app-win32-x64.zip?csf=1&web=1&e=hY3b7S)?csf=1&web=1&e=hY3b7S). 

Also, turns out it was linked in an OSF project we shared in publications: https://osf.io/vzpm8
