### ISSUE TITLE
Sounds for shape identification when not a parallelogram

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#57]
From the interviews it seemed desirable to have some supporting indication that a trapezoid, isoceles trapezoid, right trapezoid, or kite was made. The detection of these shapes is already supported from work in Voicing (#31), but it is very easy to create a shape (e.g.,) isoceles trapezoid), but only receive feedback via Voicing that you created a trapezoid if the shape is not quite precise enough (sim does not give an indication of what is "enough" by its definitions).

We would like to try designing and implementing a sound that plays when the conditions are met that one of these shapes is made (e.g., when the Voicing would first indicate you've made that shape) **that is short and confirmatory, but not congratulatory.**

For now I believe we should design only one sound and see if it can be mapped to every shape outside of the "Parallelogram Zone". Unlike the sounds to be designed for square, rectangle, and rhombus, these sounds will specifically trigger on the combination of any parameters necessary for the shape detection.

**Comment by jessegreenberg** [comment]
This sound was added, @Ashton-Morris @BLFiedler can you please review? I added the named shape to the debugging panel, I found it helpful to test this change with ?showModelValues.

**Comment by BLFiedler** [comment]
Haha, well, there are some quirks, but the I like the idea of it...

Lets
- [ ] Remove the sound when making a concave shape

And in a separate issue, related to the experience with the sound, let's remove right angle trapezoid (made into issue here: #70)

**Comment by jessegreenberg** [comment]
>  Have the sound play when more than one vertex is move or a side is moved (I don't hear the sound when making an isoceles trapezoid from another trapezoid while moving side AB for example)

Hmm, this is an issue with our angle tolerance interval. When dragging a side when the shape is not a parallelogram the value becomes negative infinity, so no angles are equal in the model and the shape name is null.

**Comment by jessegreenberg** [comment]
I just committed a potential fix for this. It uses a different tolerance interval for detecting shapes. So now we have 
- `angleToleranceInterval` which behaves like this: https://github.com/phetsims/quadrilateral/blob/179b37e946eaa871429eba931ae1ca994cefac47/js/quadrilateral/model/QuadrilateralShapeModel.ts#L161-L204
- `shapeAngleToleranceInterval`, which is always a constant value. I think this works OK because certain shapes that must be a parallelogram can only be acheived if angle equalities are equal within `shapeAngleToleranceInterval` AND the shape is a parallelogram. But it doesn't suffer from side effects of doing odd things to the angleToleranceInterval during interaction.
