### ISSUE TITLE
Make side length maintenance a layer to parallelogram maintenance

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#59]
After interviewing on the sim, I would like to try adding side length maintenance of a parallelogram as a layer on top of the parallelogram maintenance, rather than a separate "mode"/checkbox/screen, while also making it more difficult to achieve (it was easy for participants to second guess themselves with the amount of stretch the sides could do). 

- [x] 1. Let's borrow the "choir" success sound from Success category Collection 4 and have it play instead of the parallelogram maintenance sound (from Collection 1) when the conditions for side length maintenance (#25) are met.
- [x] 2. Decrease the default value of lengthToleranceIntervalScaleFactor by half.

To think about: Is there an easy solution for preventing someone from wiggling their mouse or finger back and forth (very small stretches) and hearing the length maintenance sound?

**Comment by jessegreenberg** [comment]
Sound code is getting messy in this sim...But I think this is done. I made this behavior a new paradigm to be selected in the Preferences Dialog called "Maintenance Sounds" that is now the default design.
![image](https://user-images.githubusercontent.com/6396244/153951481-a19c88e5-fc4c-4e0b-b4ef-256ef909050c.png)

And the default `lengthToleranceIntervalScaleFactor` value was reduced by half.

@BLFiedler reassigning to you to review the behavior.

**Comment by BLFiedler** [comment]
Ideal behavior: The "choir" or side length maintenance sound should only play after a learner makes a concerted effort to maintain side lengths. The parallelogram maintenance sound can play immediately during side movement.

**Comment by jessegreenberg** [comment]
Over slack I said:
> Last we spoke I think we thought that there was a delay before the maintenance sound every time you dragged a side/vertex. I don't think that is the case anymore. The delay was only after the equal lengths condition was lost. We can make the delay happen every time you start a new interaction. But that won't work well with the tangible.
I can see now there is already other sound code counting number of vertices pressed, which won't work well with the tangible. Should I proceed with what would work well with screen interaction or should we take a step back and reconsider?

**Comment by jessegreenberg** [comment]
I went forward with a delay when interaction starts with the quad. But this won't work with the tangible for the reason described above.  Assigning to @BLFiedler to review.

**Comment by BLFiedler** [comment]
One solution we could try:

- Require specific amount of angle change along with the side length maintenance before side maintenance success sound plays. E.g., when within lengthToleranceInterval, require angle change of 2*angleToleranceInterval. Compare to initial angle saved at each new length maintenance arc. New arc, new initial angle to compare against. 

Let's also make sure it's not possible for the choir sound to play forever when the shape is not changing :)

**Comment by jessegreenberg** [comment]
The solution proposed in https://github.com/phetsims/quadrilateral/issues/59#issuecomment-1048004794 has been implemented in the above commit. Here is a dev version with it implemented so that we can compare it to a different behavior if we want.
https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.21/phet/quadrilateral_en_phet.html

**Comment by jessegreenberg** [comment]
Discussion on slack:

Brett Fiedler  1:30 PM
Ooo.. while I suspect that case will not be frequent (it's hard neough to maintain in one direction), I don't think we want that.





1:30
Can we eliminate the requirement once the threshold has been passed once for one arc?

Jesse Greenberg  1:32 PM
Ah, yes I think so. Ill try that.
1:33
Do you think this will be specific to the choir sound or will Voicing describe this case as well?
New

Brett Fiedler  1:34 PM
Voicing is likely to continue to assert that you're maintaining side length still, but I don't think it will differentiate the change in direction.

**Comment by jessegreenberg** [comment]
The proposal in https://github.com/phetsims/quadrilateral/issues/59#issuecomment-1049093974 was implemented in the above commit and can be tested at this dev version: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.22/phet/quadrilateral_en_phet.html

The result of this change (which I think is expected) is that if you pick up a side, drag it along the arc, release, then pick ANY side, there will not be delay for the choir sound because the angles have changed enough from the set saved when a new set of side lengths was stored. Unsure if this is a problem.

Another solution I thought of was to add an "angleVelocity" to the model. The choir sound will only play if there is a certain amount of angular velocity for the changing vertices. If you stop moving the choir sound will stop playing, and there will be a delay before playing the choir sound until you keep moving along the arcs for a certain amount of time. I won't try it until I hear from @BLFiedler.

@BLFiedler assigning to you to review what we have so far.
