### ISSUE TITLE
Implement initial visual design

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#60]
This issue will be for creating this initial pass of the visual design

This pass includes: Dynamic lengths, angle guides, background color changes, checkbox controls for corner labels and angle guides.

To be covered still:
- Visual changes when achieving a parallelogram
- Visual changes during special parallelogram cases (all side lengths equal, all angles 90)
- Start up interaction hints

**Comment by BLFiedler** [comment]
I shared this design with JG and TS during the last virtual model meeting.

### Mockups
![Startup](https://user-images.githubusercontent.com/47331395/153247756-6cdca456-d35d-4f48-bac0-8575c178a0ec.png)

![Startup_allchecked](https://user-images.githubusercontent.com/47331395/153247773-57683439-251d-4ed0-b9a1-9a56f99fbc56.png)

![parallelogram_angleschecked](https://user-images.githubusercontent.com/47331395/153247784-95830f7a-3871-45bd-8779-68ef68373ecf.png)

![irregularquad](https://user-images.githubusercontent.com/47331395/153247793-13f43760-d75d-4ef9-a8fc-f9ee772f28cd.png)

### Colors used (RGB)
Focus Pink shape: 250 51 141
Desaturated blue background: 167 167 255
Angle guide grey: 100 100 100

### Notable modifications

1. Play area boundary slightly rounded at edges. This can just be aesthetic since the vertices are also rounded with a larger corner radius.
2. Background color changed from dark blue to a desaturated tone of the same blue.

### Additions

#### Shape (Vertices and sides)

#### Angle guides

#### Corner labels

- Labels center on the vertices. Currently labeled 1,2,3,4 from top left, clockwise which I believe matches the currently Voicing. This should change if the Voicing changes.

#### Control area options

- Checkboxes vertically centered with the play area (landscape)

**Comment by BLFiedler** [comment]
Assigning @jessegreenberg to begin implementation! 🥳 

I occasionally present a few other options for each feature that differ from the mockups - feel free to implement those instead if it is significantly easier and we can assess it at that point first.

Ping me here or in Slack for any questions that crop up ahead of design meeting.

**Comment by jessegreenberg** [comment]
Excellent! Collecting questions in this comment:
 - [ ] The vertices are going to be displayed circular but are square in the model (for hit detection with other sides and vertices). Is this OK?

**Comment by BLFiedler** [comment]
Responses as of 2/14:

> Excellent! Collecting questions in this comment:
> 
> * [x]  The vertices are going to be displayed circular but are square in the model (for hit detection with other sides and vertices). Is this OK?
> * [x]  Similar question for the sides and their tapered width. Sides have a defined width in the model for hit detection, is it OK that the taper is purely graphical?

Yeah, I expected both of these!

> * [x]  If the side segments are based on the size of the vertex, they aren't really based on the model value for the side width (more of a code consideration). What if we made the side width larger so that the initial side segment matches the model value for the side width.

This is probably fine. As long as the vertex grab takes precedence (is in "front"). I just don't think we'll want the grabbable area of the side to exceed the vertex width.

> * [x]  >For the purposes of visualization, I think the first segment may need to be a bit longer...While playing with it it didn't seem necessary, but we can certainly do something like this.

Yeah, I suppose that feels true here after playing with it.
 
> * [x]  At 5% taper per segment the sides can get very slim when the sides are stretched all the way across the play area.

It does. I'm not sure if that's a problem yet. Let's go ahead and retain the hit detection and pointer area for drag even with the small width and see how that feels for now.

**Comment by BLFiedler** [comment]
For archival purposes, the appearance I played with in answering the above:
![Quadrilateral screenshot](https://user-images.githubusercontent.com/47331395/153892607-0b2b1d6d-5c62-42ca-b02d-413ad8710b1b.png)

**Comment by jessegreenberg** [comment]
Discussed some points wiht @BLFiedler 
- [ ] To get around issues of side occlusion and angle difference from side taper, we are going to center the arcs of the angle guide on each vertex. The guide will be a "donut" around each vertex so that the vertex itself and the corner labels are not occluded.
- [ ] It IS important that the angle guides rotate with the shape. To accomplish this the starting angle of the guide will be locked to the one of the side segments(largest one).
- [ ] The model width for sides should be constant across the length, ignoring taper. Mouse/touch areas should match model width and ignore taper.

**Comment by jessegreenberg** [comment]
OK, I think what is described in this issue has been implemented, including the angle guides and notes in https://github.com/phetsims/quadrilateral/issues/60#issuecomment-1039308535. Mouse/touch areas for sides can be verified again with ?showPointerAreas.

This is ready for your review @BLFiedler .

**Comment by BLFiedler** [comment]
- [ ] Eliminate the taper on the side lengths but maintain the segments and telescoping effect.

This is to address the fact that the shape stops looking like a shape and introduces asymmetry. Also, it will bring the visuals in line with the pointer areas.

**Comment by jessegreenberg** [comment]
OK I think I am caught up to spec here. Ready for review. Just noting some things that may or may not be important.

1) Without the taper there isn't a need for custom mouse/touch areas. The sides are the touch areas and you won't see a unique highlight with ?showPointerAreas.
2) If the angle guides are invisible when at right angle, the "Angle Guides" checkbox does nothing if pressed on sim startup.
3) There are oddities going on because all of the angle checks here use the same angleToleranceInterval as the one used to determine if it is a parallelogram. So there are cases currently where right angle indicators are displayed when the model thinks we are not a parallelogram.

**Comment by jessegreenberg** [comment]
For #3 above, @BLFiedler suggested on slack

We can either gate it within being a parallelogram or tighten the 90 tolerance. I'm leaning toward the latter though.

Ill add another tolerance variable just for the 90 degree indicators and see how it goes.

**Comment by jessegreenberg** [comment]
I added a new tolerance that controls when right angle indicators are displayed. Can be controlled with `?rightAngleIndicatorToleranceInterval`. Default value is 0.025. This value does not change with input like the `angleToleranceInterval`.

OK assigning to @BLFiedler to review the last three comments and the current behavior of the simulation.

**Comment by jessegreenberg** [comment]
I see, sorry I misread that. Fixed in the above commit. With this behavior I think there may not be a tolerance issue anymore. Now the right angle indicators can only be visible if the shape is a square or rectangle. And we can only have square or rectangle if the model is in a parallelogram state. Back to @BLFiedler for review.

**Comment by BLFiedler** [comment]
Visual tweaks are ongoing in other issues.
