### ISSUE TITLE
Rename vertices from numeric to alphabetical in the model

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#67]
In https://github.com/phetsims/quadrilateral/issues/60, vertices will be labeled from 1,2,3,4 to A,B,C,D. The model references them by number. Model and view should match if design is going to label these with letters.

**Comment by jessegreenberg** [comment]
Also, these should be made translatable graphically if we are going to commit to alphabetical labels (I think...)

**Comment by terracoda** [comment]
We decided to rename the corner, right? Visually, they have been renamed.

**Comment by BLFiedler** [comment]
Yes - I've just deferred this a moment while I determine if there are any issues we run into for the translation of the letters. Is it clear to you how to proceed with that @jessegreenberg?

I'm most hesitant I guess if we decide to use lowercase with the sides since not every alphabet has case. Any thoughts?

**Comment by jessegreenberg** [comment]
Above commit renamed model variables.

**Comment by jessegreenberg** [comment]
Labels are now translatable:
![image](https://user-images.githubusercontent.com/6396244/154998234-c0fecd51-3d08-492a-a2f6-7ecd661665ff.png)

**Comment by jessegreenberg** [comment]
I don't see any direct reference to the vertices in the electron App. So I think that is it for most of this issue.

**Comment by jessegreenberg** [comment]
No, those come from the string test with `?stringTest=double`.
